In [148]:
import torch

In [149]:
torch.__version__

'2.5.1+cu118'

In [150]:
#scaler 
scaler = torch.tensor(6)
scaler , scaler.ndim, scaler.item()

(tensor(6), 0, 6)

In [151]:
# create vector of tensors
vector = torch.tensor([7,7])
vector, vector.ndim

(tensor([7, 7]), 1)

In [152]:
# how to identify the shape of tensor
vector.shape, scaler.shape

(torch.Size([2]), torch.Size([]))

In [153]:
# matrix
matrix = torch.Tensor([[4,7], [5,6]])
matrix, matrix.ndim

(tensor([[4., 7.],
         [5., 6.]]),
 2)

In [154]:
matrix.shape

torch.Size([2, 2])

In [155]:
d3_tensor = torch.Tensor([[[1, 2, 3],
                            [4,5,6],
                            [6,7,9]]])
d3_tensor, d3_tensor.ndim, d3_tensor.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [6., 7., 9.]]]),
 3,
 torch.Size([1, 3, 3]))

In [156]:
# create tensor with random values
random_tensor = torch.rand(size = (4,3))
random_tensor

tensor([[0.8030, 0.9684, 0.6387],
        [0.8675, 0.9961, 0.0968],
        [0.9422, 0.3773, 0.0636],
        [0.2928, 0.4109, 0.2762]])

In [157]:
# check the shape of the tensor
random_tensor.shape, random_tensor.ndim

(torch.Size([4, 3]), 2)

In [158]:
random_tensor.dtype

torch.float32

In [159]:
x_tensor = torch.rand(size = (4,4,3))
x_tensor, x_tensor.ndim, x_tensor.shape

(tensor([[[0.6799, 0.7057, 0.3646],
          [0.4317, 0.1133, 0.7889],
          [0.0454, 0.7025, 0.0162],
          [0.2005, 0.4547, 0.4769]],
 
         [[0.4005, 0.8770, 0.8587],
          [0.2354, 0.8636, 0.5300],
          [0.3334, 0.2498, 0.9214],
          [0.3220, 0.9876, 0.7927]],
 
         [[0.3059, 0.9647, 0.1610],
          [0.6948, 0.3020, 0.5899],
          [0.2021, 0.4545, 0.8396],
          [0.7153, 0.2387, 0.9846]],
 
         [[0.7793, 0.2544, 0.0602],
          [0.4532, 0.8916, 0.7942],
          [0.8908, 0.4865, 0.6982],
          [0.6697, 0.1411, 0.8502]]]),
 3,
 torch.Size([4, 4, 3]))

In [160]:
x_tensor = torch.rand(size = (224,224,3))
x_tensor.ndim

3

In [161]:
# zeros ones

zero_tensor = torch.zeros(size = (3,4,5))
zero_tensor, zero_tensor.ndim, zero_tensor.shape, zero_tensor.dtype

(tensor([[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]),
 3,
 torch.Size([3, 4, 5]),
 torch.float32)

In [162]:
ones_tensor = torch.ones(size=(3,4,5)) 
ones_tensor, ones_tensor.ndim, ones_tensor.shape, ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]),
 3,
 torch.Size([3, 4, 5]),
 torch.float32)

In [163]:
# arange

t_tensor = torch.arange(0,10,1)
t_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# next session

In [164]:
r_tnsor = torch.tensor( data = [4, 5, 9], dtype= torch.float32, device="cpu",requires_grad=False) 
r_tnsor, r_tnsor.dtype, r_tnsor.device

(tensor([4., 5., 9.]), torch.float32, device(type='cpu'))

In [165]:
#tensor operations
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [166]:
x= x+10
x

tensor([11, 12, 13])

In [167]:
x=x-2
x

tensor([ 9, 10, 11])

In [168]:
x = x*2
x

tensor([18, 20, 22])

In [169]:
x = x/ 2
x

tensor([ 9., 10., 11.])

In [170]:
y =x*x
y

tensor([ 81., 100., 121.])

In [171]:
x = torch.multiply(x, 10)
x

tensor([ 90., 100., 110.])

In [172]:
x = torch.matmul(x, x)

In [173]:
x

tensor(30200.)

In [174]:
tensor_a = torch.rand(size=(2,3))
tensor_a, tensor_a.shape

(tensor([[0.6411, 0.4269, 0.0427],
         [0.9339, 0.2598, 0.1453]]),
 torch.Size([2, 3]))

In [175]:
tensor_b = torch.rand(size=(2,3))
tensor_a, tensor_b.shape

(tensor([[0.6411, 0.4269, 0.0427],
         [0.9339, 0.2598, 0.1453]]),
 torch.Size([2, 3]))

In [176]:
tensor_f = torch.matmul(tensor_a, tensor_b)
tensor_f
# error cause of incompatible shapes

In [177]:
tensor_b = torch.rand(size=(3,3))

In [178]:
tensor_f = torch.matmul(tensor_a, tensor_b)
tensor_f

tensor([[0.1711, 0.3896, 0.6746],
        [0.2624, 0.5152, 0.7552]])

In [179]:
# manual seed generation

random_tensor = torch.rand(size=(2,3))

torch.manual_seed(42)

In [180]:
from torch import nn

In [181]:
linear_layer = nn.Linear(in_features=6, out_features=4)
tensor_L = torch.rand(size=(4,6))

x = linear_layer(tensor_L)
x

tensor([[-0.2434,  0.3834,  0.5471, -0.5207],
        [ 0.3196,  0.0989,  0.2882, -0.3769],
        [ 0.2388,  0.0468,  0.4468, -0.5620],
        [ 0.1496,  0.0345,  0.3124, -0.4033]], grad_fn=<AddmmBackward0>)

In [182]:
v = torch.arange(0, 20, 3)
v

tensor([ 0,  3,  6,  9, 12, 15, 18])

In [183]:
v.min(), v.max()

(tensor(0), tensor(18))

In [184]:
max_index= v.argmax()
max_index

tensor(6)

In [185]:
min_index = v.argmin()
min_index

tensor(0)

In [186]:
float_tensors = torch.arange(2., 10., 1.)
float_tensors, float_tensors.dtype

(tensor([2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [187]:
float_tensors = torch.arange(2, 10, 1)
float_tensors, float_tensors.dtype

(tensor([2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

# next session

In [188]:
#transpose
random_tensor, random_tensor.shape

(tensor([[0.2960, 0.4045, 0.1699],
         [0.8645, 0.4269, 0.5194]]),
 torch.Size([2, 3]))

In [189]:
random_tensor_t = torch.transpose(random_tensor, 0, 1)
random_tensor_t, random_tensor_t.shape

(tensor([[0.2960, 0.8645],
         [0.4045, 0.4269],
         [0.1699, 0.5194]]),
 torch.Size([3, 2]))

In [190]:
random_tensor_tv2 = random_tensor.t()
random_tensor_tv2, random_tensor_tv2.shape

(tensor([[0.2960, 0.8645],
         [0.4045, 0.4269],
         [0.1699, 0.5194]]),
 torch.Size([3, 2]))

In [191]:
#mean of some tensor
mean_tensor = torch.arange(0, 10, 1)
mean_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
mean_tensor_f32 = mean_tensor.type(torch.float32)
mean_tensor_f32

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [193]:
mean_tensor_r = mean_tensor_f32.mean()
mean_tensor_r

tensor(4.5000)

In [194]:
#reshape a tensor

mean_tensor_f32.shape

torch.Size([10])

In [195]:
reshape_tensor = mean_tensor_f32.reshape(1,-1)
reshape_tensor, reshape_tensor.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [196]:
reshaped_tensorv2 = mean_tensor_f32.reshape(2,5)
reshaped_tensorv2

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [197]:
x_stacked  = torch.stack([x,x,x,x], dim = 0)

x_stacked, x_stacked.shape

(tensor([[[-0.2434,  0.3834,  0.5471, -0.5207],
          [ 0.3196,  0.0989,  0.2882, -0.3769],
          [ 0.2388,  0.0468,  0.4468, -0.5620],
          [ 0.1496,  0.0345,  0.3124, -0.4033]],
 
         [[-0.2434,  0.3834,  0.5471, -0.5207],
          [ 0.3196,  0.0989,  0.2882, -0.3769],
          [ 0.2388,  0.0468,  0.4468, -0.5620],
          [ 0.1496,  0.0345,  0.3124, -0.4033]],
 
         [[-0.2434,  0.3834,  0.5471, -0.5207],
          [ 0.3196,  0.0989,  0.2882, -0.3769],
          [ 0.2388,  0.0468,  0.4468, -0.5620],
          [ 0.1496,  0.0345,  0.3124, -0.4033]],
 
         [[-0.2434,  0.3834,  0.5471, -0.5207],
          [ 0.3196,  0.0989,  0.2882, -0.3769],
          [ 0.2388,  0.0468,  0.4468, -0.5620],
          [ 0.1496,  0.0345,  0.3124, -0.4033]]], grad_fn=<StackBackward0>),
 torch.Size([4, 4, 4]))

In [198]:
k= torch.arange(0,10,1)
k, k.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [199]:
k_mod = k.reshape(1,-1)
k_mod, k_mod.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [200]:
k_mod_v2 = k_mod.squeeze()
k_mod_v2, k_mod_v2.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [201]:
k_mod_v3 = k_mod_v2.unsqueeze(dim = 0)
k_mod_v3, k_mod_v3.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [202]:
k_mod_v3 = k_mod_v2.unsqueeze(dim = 1)
k_mod_v3, k_mod_v3.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([10, 1]))

In [203]:
# permute
i = torch.rand(224,228,3)
i_permute = i.permute(2,1,0)
i_permute, i_permute.shape

(tensor([[[0.1165, 0.1225, 0.6183,  ..., 0.1374, 0.1522, 0.6306],
          [0.7071, 0.9348, 0.1305,  ..., 0.0650, 0.2109, 0.9148],
          [0.8913, 0.6648, 0.4313,  ..., 0.4482, 0.9351, 0.8127],
          ...,
          [0.0837, 0.6430, 0.2574,  ..., 0.1490, 0.5788, 0.5614],
          [0.8423, 0.3279, 0.4450,  ..., 0.3416, 0.3428, 0.9065],
          [0.7801, 0.5391, 0.4811,  ..., 0.2840, 0.6011, 0.4370]],
 
         [[0.9103, 0.1341, 0.8742,  ..., 0.3852, 0.3084, 0.7926],
          [0.6581, 0.7992, 0.7235,  ..., 0.1280, 0.1842, 0.4759],
          [0.1447, 0.9746, 0.3381,  ..., 0.8423, 0.7995, 0.0742],
          ...,
          [0.0150, 0.5226, 0.7453,  ..., 0.8975, 0.3847, 0.0072],
          [0.0293, 0.4942, 0.0608,  ..., 0.2586, 0.5288, 0.5970],
          [0.7698, 0.4647, 0.4079,  ..., 0.2329, 0.5635, 0.3062]],
 
         [[0.6440, 0.7565, 0.4835,  ..., 0.7029, 0.0165, 0.7700],
          [0.4913, 0.5783, 0.1621,  ..., 0.0728, 0.4808, 0.8573],
          [0.5315, 0.1774, 0.3103,  ...,

# next session

In [204]:
x = torch.rand(2,2,3)
x

tensor([[[0.5609, 0.0762, 0.8487],
         [0.1435, 0.7281, 0.8682]],

        [[0.7240, 0.6005, 0.7844],
         [0.6948, 0.2316, 0.5119]]])

In [205]:
x[0]

tensor([[0.5609, 0.0762, 0.8487],
        [0.1435, 0.7281, 0.8682]])

In [206]:
x[0][0]

tensor([0.5609, 0.0762, 0.8487])

In [207]:
x[0][0][2]

tensor(0.8487)

In [208]:
import numpy as np

In [209]:
r = np.arange(1.0, 7.0)
r, type(r)

(array([1., 2., 3., 4., 5., 6.]), numpy.ndarray)

In [210]:
r_tensor = torch.from_numpy(r)
type(r_tensor)

torch.Tensor

In [211]:
x= torch.arange(0, 10, 1)
type(x)

torch.Tensor

In [212]:
x_numpy = x.numpy()
type(x_numpy)

numpy.ndarray

In [213]:
# set the maunaul seed
torch.manual_seed(42)

random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [214]:
!nvidia-smi 

Sat Jan  4 18:29:56 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.61                 Driver Version: 531.61       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060       WDDM | 00000000:01:00.0  On |                  N/A |
| N/A   58C    P8               11W /  N/A|    797MiB /  6144MiB |     16%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [215]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [216]:
torch.cuda.device_count()

1

In [217]:
tensor = torch.tensor([2,5])
tensor, tensor.device

(tensor([2, 5]), device(type='cpu'))

In [218]:
tensor_gpu = tensor.to('cuda')